[env]
TERM = "xterm-256color"

[terminal]
shell = "/bin/zsh"

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }

[window]
opacity = 0.95
