[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }

[window]
opacity = 0.9
